### ISSUE TITLE
MFM doesn't show more than one italic

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8731] opened 2022-05-25 04:44 UTC
## 💡 Summary

If a post is made like

```
This should *be in italics*

This should *also be in italics*
```

only the "also be in italics" part is italicized.  

## 🥰 Expected Behavior

Any `*text*` should be italicized

## 🤬 Actual Behavior

![Screenshot_20220524-214152_1.png](https://user-images.githubusercontent.com/44733677/170181471-b1cb034a-736a-45bf-b2a7-313985dab1e1.png)

## 📌 Environment

Misskey version: Latest git (12.110.1)
Your OS: Android, Linux
Your browser: Bromite, Firefox

**Comment by Johann150** [comment] 2022-05-25 05:57
It is not related to the number of times you use the italic syntax. It doesn't work in the first case because of the hyphen. As such, your example from the summary actually works.

Duplicate of https://github.com/misskey-dev/mfm.js/issues/102

**Closed as not planned by Johann150** 2022-05-25 05:57 UTC
Labels: ⚠️bug?

**Comment by ThatOneCalculator** [comment] 2022-05-25 06:08
Ah, gotcha. I was wondering why it was so hard to reproduce :smile:
