### ISSUE TITLE
Improvement of rate limiting error message

### ISSUE THREAD

**Issue by osapon** [syuilo/Misskey#14882] opened 2024-11-02 14:03 UTC
### Summary

If reach the limit on an operation that has a limit on the count of times it can be executed, such as exporting, I got the error message "Rate limit exceeded. Please try again later."

It would be nice if they could show me the interval limit set by the server and how long it will take to recover.

### Purpose

This saves I the trouble of having to retry multiple times without knowing when the limit will be restored.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by Sayamame-beans** [comment] 2024-11-02 16:38
duplicate of #13996

**Closed as not planned by Sayamame-beans** 2024-11-02 16:38 UTC
Labels: ✨Feature
