### ISSUE TITLE
猫耳の色を耳の付け根から取得する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [syuilo/Misskey#10377] opened 2023-03-21 06:50 UTC
## Summary

タイトルのとおりです

[Misskey.io サポート](https://support.misskey.io/hc/ja/community/posts/6598484350095)にて上がった話題に対応

## イメージ画像

![image](https://user-images.githubusercontent.com/67428053/226535740-c91f1542-0338-4664-ad5d-348f980bf843.png)

**Comment by ThatOneCalculator** [comment] 2023-03-21 07:01
The cat ear color is retrieved from the blurhash of the avatar, and analyzing every profile pic for per-pixel values would probably be too expensive.

**Comment by kakkokari-gtyih** [comment] 2023-03-21 07:03
I am not good at backend implementation, so I made the [implementation on the frontend](https://github.com/kakkokari-gtyih/misskey/commit/640fd313ea4d36ada74cbf5b020bf96f06a319ee) for reference, but it would be better to generate and store the colors on the backend.

バックエンドの実装に関してはよくわからない部分が多かったためフロントエンドでの実装例を作ってみたのですが、実際はバックエンドにて事前に生成して置いておくほうが良いとおもいます

**Comment by ThatOneCalculator** [comment] 2023-03-21 07:36
Storing colors on the backend is essentially what blurhash already does

**Comment by kakkokari-gtyih** [comment] 2023-03-21 10:23
I know, but the blurhash algorithm does not match the ear color with the color around the ear in the image, making it unnatural.
I also tried a method of averaging the colors of the pixels decoded using the blurhash library that were closer to the base of the ear, but the effect was not nearly as apparent.

**Comment by acid-chicken** [comment] 2023-03-21 11:28
Duplicate of #10251

**Closed as not planned** 2023-03-21 11:28 UTC
