### ISSUE TITLE
Notifications for Follow Request are duplicated on UI

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#14929] opened 2024-11-09 11:15 UTC
### 💡 Summary

see **Steps to Reproduce**

### 🥰 Expected Behavior

normal operation

### 🤬 Actual Behavior

see below

### 📝 Steps to Reproduce

1. Set up two accounts: Account A (hereinafter referred to as A) requires follow requests, while Account B (hereinafter referred to as B) has no specific requirements
2. Use B to make a follow request to A
3. At this point, A will display a follow request notification and directly reject it
4. Return to B, and send a follow request to A again
5. Return to A, and you will find two follow request notifications. However, the database only has a record of one request, and only the latest follow request can be approved or rejected. The earlier notification is clickable but has no actual effect

If we check the contents in Redis now, we’ll find that the previous records haven’t been cleared. Unlike when a follow request is accepted, there is no record indicating that earlier follow requests should not be displayed. If you repeat the steps above, you’ll eventually end up with countless follow request notifications. This is clearly a bug.

### 💻 Frontend Environment

```markdown
* Misskey: 2024.11.0-alpha.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Misskey: 2024.11.0-alpha.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by KisaragiEffective** [comment] 2024-11-11 00:15
this is known issue.
Duplicate of #13378

**Closed as not planned by KisaragiEffective** 2024-11-11 00:15 UTC
Labels: packages/frontend, ⚠️bug?
