### ISSUE TITLE
Misskey can't be terminated

### ISSUE THREAD

**Issue by MomentQYC** [syuilo/Misskey#11658] opened 2023-08-10 16:54 UTC
## 💡 Summary

After successfully starting Misskey by running a command such as npm start or pnpm dev, Misskey cannot be terminated using CTRL+C.
## 🥰 Expected Behavior

Misskey will terminate without incident.
## 🤬 Actual Behavior

Misskey can never be terminated by using CTRL C.
## 📝 Steps to Reproduce

1. `npm start`/`pnpm dev`
2. Ctrl+C

### 💻 Frontend
* Model and OS of the device(s): Windows 11 / Android 12 / iOS 16
  
* Browser: Edge 115
  
* Server URL: -
  
* Misskey: 13.14.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: systemd / manually
* Misskey: 13.14.2
* Node: 18.16.x
* PostgreSQL: 15.4
* Redis: 7.0.5
* OS and Architecture: 
Ubuntu 20.04 amd64 / Windows 11 amd64

**Comment by kakkokari-gtyih** [comment] 2023-08-11 13:53
Duplicate of https://github.com/misskey-dev/misskey/issues/10995 ?

**Comment by tamaina** [comment] 2023-08-11 14:04
Duplicate of https://github.com/misskey-dev/misskey/issues/10995

**Closed as not planned by tamaina** 2023-08-11 14:04 UTC
Labels: 🐛Bug, packages/backend
