### ISSUE TITLE
Cannot import custom emojis due to unzipper bug

### ISSUE THREAD

**Issue by pbzweihander** [syuilo/Misskey#11139] opened 2023-07-06 11:32 UTC
## 💡 Summary

Cannot import batch emojis due to unzipper bug: https://github.com/ZJONSSON/node-unzipper/issues/271

## 🥰 Expected Behavior

Able to import large emoji zip files

## 🤬 Actual Behavior

```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at DuplexWrapper.<anonymous> (file:///misskey/packages/backend/built/queue/processors/ImportCustomEmojisProcessorService.js:67:31)
    at DuplexWrapper.emit (node:events:513:28)
    at Writable.<anonymous> (/misskey/node_modules/.pnpm/unzipper@0.10.14/node_modules/unzipper/lib/extract.js:44:15)
    at Writable.emit (node:events:525:35)
    at finish (node:internal/streams/writable:748:10)
    at finishMaybe (node:internal/streams/writable:733:9)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at ProxyWriter.emit (node:events:525:35)
    at FileWriter.emit (node:events:513:28)
    at end (/misskey/node_modules/.pnpm/fstream@1.0.12/node_modules/fstream/lib/writer.js:324:14)
    at /misskey/node_modules/.pnpm/fstream@1.0.12/node_modules/fstream/lib/writer.js:314:34
    at endUtimes (/misskey/node_modules/.pnpm/fstream@1.0.12/node_modules/fstream/lib/writer.js:238:46)
    at setProps (/misskey/node_modules/.pnpm/fstream@1.0.12/node_modules/fstream/lib/writer.js:297:5)
    at /misskey/node_modules/.pnpm/fstream@1.0.12/node_modules/fstream/lib/writer.js:287:7
    at callback (/misskey/node_modules/.pnpm/graceful-fs@4.2.11/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:209:5)
```

## 📝 Steps to Reproduce

Trying to import this zip file fails: [blobs-misskey.zip](https://github.com/misskey-dev/misskey/files/11967690/blobs-misskey.zip)

Trying to unzip above file with this code:

```typescript
import * as unzipper from "unzipper";
import * as fs from "node:fs";

const unzipStream = fs.createReadStream("blobs-misskey.zip");
const extractor = unzipper.Extract({ path: "output" });
unzipStream.pipe(extractor);
```

And the output folder's `meta.json` file is corrupted.

### 💻 Frontend
* Model and OS of the device(s):
* Browser: Firefox
* Server URL: pbzweihander.social
* Misskey:13.13.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: AWS EKS
* Misskey: 13.13.2
* Node: 18.16.0
* OS: bottlerocket

**Comment by pbzweihander** [comment] 2023-07-06 11:33
I think we should replace node-unzipper with something like yauzl

**Comment by acid-chicken** [comment] 2023-07-06 11:44
Duplicate of #10778

**Closed as not planned** 2023-07-06 15:31 UTC
Labels: ⚠️bug?
