### ISSUE TITLE
Federate Avatar Decorations

### ISSUE THREAD

**Issue by Mar0xy** [syuilo/Misskey#12574] opened 2023-12-04 20:37 UTC
### Summary

Avatar Decorations were added in October but to this day still don't federate which I feel like is a major oversight.

### Purpose

That the Avatar Decorations should federate with other Misskey instances and Misskey's corresponding forks.

**Comment by tai-cha** [comment] 2023-12-05 11:10
Duplicate of #12151
WIP on #12154

**Closed as not planned by tai-cha** 2023-12-05 11:10 UTC
Labels: ✨Feature
