### ISSUE TITLE
pull-to-refresh not working on mobile after sign-in

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#11458] opened 2023-08-04 11:40 UTC
## 💡 Summary

After sign in, pulling the page does not trigger refresh. You have to manually go to the address tab and click the refresh bottom to refresh the page.
## 🥰 Expected Behavior
Pull to refresh working.
If you dont sign in, or if you have a older version (e.g. v13.11.0). It should look like this when you refresh the timeline

https://github.com/misskey-dev/misskey/assets/106132975/ae5a34d4-c1af-4fea-aaa7-e616a8a8daed

## 🤬 Actual Behavior

After you sign in, pull to refresh stop functioning. Pulling the page triggers nothing.

https://github.com/misskey-dev/misskey/assets/106132975/181969a3-d36f-4e6e-8833-8db0b938d063

## 📝 Steps to Reproduce

1. sign in 
2. pull to refresh

### 💻 Frontend
* Model and OS of the device(s): iPhone 13 Pro
  

* Browser: Safari
  

  
* Misskey: 13.14.2

**Comment by tamaina** [comment] 2023-08-04 11:43
Duplicate of https://github.com/misskey-dev/misskey/issues/10964

**Closed as not planned by tamaina** 2023-08-04 11:43 UTC
Labels: ⚠️bug?
