### ISSUE TITLE
Unable to scroll through dropdown options

### ISSUE THREAD

**Issue by Freeplayg** [syuilo/Misskey#7957] opened 2021-11-05 17:20 UTC
## 💡 Summary

The list of items in a dropdown go off screen, and there is no scrolling.

https://user-images.githubusercontent.com/40742947/140552152-c11fa3de-9015-4938-a57c-105da907ae45.mp4

## 🙂 Expected Behavior

A scrollbar would let me scroll through the list

## ☹️ Actual Behavior

There is no scrollbar, content goes off screen

## 📝 Steps to Reproduce

1. Find a dropdown with a very long list that goes off the screen
2. Try to scroll

## 📌 Environment

Firefox 93
Linux Pop! OS 21.04

**Comment by syuilo** [comment] 2021-11-06 04:52
Duplicate of https://github.com/misskey-dev/misskey/issues/7946

This issue has been fixed

**Closed as completed by syuilo** 2021-11-06 04:52 UTC
Labels: ⚠️bug?
