### ISSUE TITLE
Can't react with custom emoji

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#10528] opened 2023-04-08 14:14 UTC
## 💡 Summary

since 13.11.0 
I can't send reactions using custom emoji. Only utf8 reactions are working.

## 🥰 Expected Behavior

I expect to react with any emoji

## 🤬 Actual Behavior

no reaction while using custom emoji

## 📝 Steps to Reproduce

1. just react with any custom emoji to local or remote notes

## 📌 Environment

Misskey version: 13.11.0
Your OS: docker
Your browser: firefox 111

**Comment by tamaina** [comment] 2023-04-08 14:15
Duplicate of 10502

**Closed as not planned by tamaina** 2023-04-08 14:15 UTC
Labels: ⚠️bug?

**Comment by tassoman** [comment] 2023-04-08 14:18
but in english  🥲
