### ISSUE TITLE
Cannot open reaction popup after update

### ISSUE THREAD

**Issue by Hoto-Cocoa** [syuilo/Misskey#13484] opened 2024-03-01 13:15 UTC
### 💡 Summary

Users can't open the reactions popup after update.

I confirmed clearing `pizzax::base` in IndexedDB and Local Storage(`idbfallback`) solves this issue.

Here is the console log:
![image](https://github.com/misskey-dev/misskey/assets/21969938/6e7d83db-531c-462f-b535-66b0db6c2fb6)

### 🥰 Expected Behavior

Users can open reactions popup.

### 🤬 Actual Behavior

Popup not opened.

### 📝 Steps to Reproduce

1. Install old version of Misskey.
2. Use some reactions.
3. Update.
4. Try to open reactions popup.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Custom built PC, Windows 10 21H2
* Browser: Chrome 121.0.6167.189
* Server URL: https://hoto.moe
* Misskey: 2024.3.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: Docker
* Misskey: 2024.3.0
* Node: (stock docker image)
* PostgreSQL: 15
* Redis: 7
* OS and Architecture: Ubuntu 20.04.4
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tamaina** [comment] 2024-03-01 13:25
Duplicate of #13485 ?

**Comment by Hoto-Cocoa** [comment] 2024-03-01 13:27
同じ問題のようです。

**Comment by tamaina** [comment] 2024-03-01 13:27
🙏

**Closed as completed by tamaina** 2024-03-01 13:27 UTC
Labels: ⚠️bug?
