### ISSUE TITLE
Can't show notifications

### ISSUE THREAD

**Issue by ryanho** [syuilo/Misskey#13430] opened 2024-02-22 01:59 UTC
### 💡 Summary

Can't show notifications, just a blank screen.
![圖片](https://github.com/misskey-dev/misskey/assets/204075/6ca5ccc8-dea4-4309-b0f7-0d5d12a553b6)

### 🥰 Expected Behavior

Show all notification

### 🤬 Actual Behavior

Can't show notifications. I can see the related error in my browser's developer tools.
![圖片](https://github.com/misskey-dev/misskey/assets/204075/56f51f92-5fa7-4218-af1f-bea0aa2b3e4a)

### 📝 Steps to Reproduce

1. Add a test account "B" in the control panel, and use this account to follow another account "A".
2. Switch to "A" account, can see the notification message.
3. Swtich to "B" account and delete it.
4. Switch to "A" account. Notifications become blank and cannot be displayed. However, if you use the filter function, it will be displayed normally except for "Follow".

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 
* Browser:
* Server URL:
* Misskey: 2024.2.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: "Misskeyを手動で構築する" from Misskey Hub
* Misskey: 2024.2.0
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tetsuya-ki** [comment] 2024-02-22 02:23
https://github.com/misskey-dev/misskey/issues/13369 と同じっぽいです。
https://github.com/misskey-dev/misskey/pull/13412 で直される予定？

**Comment by tamaina** [comment] 2024-02-22 04:52
Duplicate of https://github.com/misskey-dev/misskey/issues/13369

**Closed as not planned by tamaina** 2024-02-22 04:52 UTC
Labels: ⚠️bug?
