### ISSUE TITLE
Broken Notifications

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#13454] opened 2024-02-24 10:50 UTC
### 💡 Summary

![immagine](https://github.com/misskey-dev/misskey/assets/92727/394d9971-ab38-49b0-9caf-12c3d0ba667c)

### 🥰 Expected Behavior

as administrator I would be informed of defective user profiles

### 🤬 Actual Behavior

Notification TL is empty. Browser's console error: "TypeError: e is undefined".
I filtered notification types, then I discovered first result is missing `userId ` object.

```json
[
  {
    "id": "9q2bnq6nn6",
    "createdAt": "2024-02-23T14:38:52.751Z",
    "type": "follow",
    "userId": "9q2biearmp"
  },
  {
    "id": "9pvk1k514g",
    "createdAt": "2024-02-18T20:59:11.797Z",
    "type": "follow",
    "userId": "97x0dxh5xn",
    "user": {
      "id": "97x0dxh5xn",
     ...................
      "onlineStatus": "unknown"
    }
  }
]
```

### 📝 Steps to Reproduce

1. install misskey 2024-02-0
2. view follow notification, filtered
3. have a following notification, without `userId ` data

### 💻 Frontend Environment

```markdown
* Misskey: 2024-02-0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: docker build master
* Misskey: 2024.02.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by tassoman** [comment] 2024-02-24 10:53
Could be happen, I've deleted spam accounts and a particular not wanted local account. 
Misskey had deleted everything about that account, except follow notification, who maybe left orphan by userId.

**Comment by 1STEP621** [comment] 2024-02-24 11:32
Duplicate of #13369, #13430
Wip on #13284 (#13412)

**Closed as not planned** 2024-02-24 13:07 UTC
Labels: ⚠️bug?
