### ISSUE TITLE
Can't display handle from bridged Bluesky account with Bridgy Fed properly

### ISSUE THREAD

**Issue by ufalsalman** [syuilo/Misskey#14941] opened 2024-11-11 11:46 UTC
### 💡 Summary

Misskey unable to show handle from bridged Bluesky account properly and just truncated before the first dot on the handle, which is dot is important on the Bluesky handle structure.

### 🥰 Expected Behavior

It's supposed to be showing the whole structure, which is `@`, `username`, then `@bsky.brid.gy`
For example, the first account is `@ufal.my.id` on Bluesky, it supposed to shown like `@ufal.my.id@bsky.brid.gy` and clickable to that profile
The second account is `@lafulock.bsky.social`, it supposed to shown like `@lafulock.bsky.social@bsky.brid.gy` and clickable

### 🤬 Actual Behavior

Based on the example, it only shows `@ufal.my.id` as `@ufal` and the rest `my.id@bsky.brid.gy` is not the part of the hyperlink and only shows as plain text, and the link is linking to `@ufal` from the same instance
For `@lafulock.bsky.social` only shows as `@lafulock` and the rest `.bsky.social@bsky.brid.gy` only shows as plain text, and the link is linking to `@lafulock` from the same instance
![Image](https://github.com/user-attachments/assets/6a6a8bc8-fbf0-4f49-a3ce-327c60cef56c)
If the mentioned account was from a post from outside of the server, for example it's from `mastodon.social`, then it would shows like `@ufal@mastodon.social` and the rest `my.id@bsky.brid.gy` is just a plain text
![Image](https://github.com/user-attachments/assets/d4905d06-608a-46de-91ca-ed85449a3652)

### 📝 Steps to Reproduce

1. Mention the account with structure like `@(handle on Bluesky)@bsky.brid.gy` on note or profile bio
2. Post the note or save the bio

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): [Custom build PC](https://static.ufal.my.id/rig.html), Windows 11 23H2 and Fedora Linux 40
* Browser: Zen Browser 1.0.1-a.18 (Firefox 132.0.1)
* Server URL: misskey.id
* Misskey: 2024.10.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment] 2024-11-11 12:00
duplicate of #9036 , https://github.com/misskey-dev/mfm.js/issues/144

**Closed as not planned by Sayamame-beans** 2024-11-11 12:00 UTC
Labels: ⚠️bug?
