### ISSUE TITLE
Alt text for custom emojis

### ISSUE THREAD

**Issue by sei0o** [syuilo/Misskey#9156] opened 2022-11-09 14:25 UTC
## Summary

Custom emojis unique to each Misskey instance come with their own "name" (something like `:ablobwobroll:`, `:erait:`; not sure how these are named). On some environments, clients show those emoji "names" instead of the emojis themselves due to platform restrictions. However, these "names" are there to be typed, not to be read, so reading them can often be difficult. Screenreaders would also struggle to express these custom emojis.

For example, [Milktea](https://github.com/pantasystem/Milktea) on Android notifies us when a note gets a reaction:

![image](https://user-images.githubusercontent.com/5410901/200848286-d7fe56a3-d8ce-41ec-ba0b-9fb43340d73d.png)

where [the original note](https://misskey.io/notes/97d8gk9r9w) is:

![image](https://user-images.githubusercontent.com/5410901/200848983-084c35e4-ec61-404e-87de-0a87711e472a.png)

### Possible Solution

A solution I have in my mind is to provide alternative ("alt") text for each emoji and to let clients use them whey they cannot use emojis. Here's some examples:

| # | emoji | emoji "name" | alt text |
|:-----|-----|------|----|
| (i) | ![image](https://user-images.githubusercontent.com/5410901/200850227-18ba14ba-6483-4553-b929-358b28be1e33.png) | `:desuyone:` | ですよね |
| (ii) | ![image](https://user-images.githubusercontent.com/5410901/200851694-318d167f-25e2-4ab6-886b-2e1eb8dc78c5.png) | `:soudasouda:` | そうだそうだ |
| (iii) | ![image](https://user-images.githubusercontent.com/5410901/200851593-9235f6e6-5cf7-4550-8466-0e40187734c9.png) | `:ablobgoodnightreverse:` | おやすみ / goodnight |
| (iv) | ![image](https://user-images.githubusercontent.com/5410901/200852513-931c0d1a-2fb6-487d-9fcb-8818fcd2815f.png) | `:sadblob:` | sad...? | 

- Alt text for (i) and (ii) will be straightforward. 
- As for (iii), there are many other similar emojis...

![image](https://user-images.githubusercontent.com/5410901/200853582-5a293282-2967-43e5-a7f0-c6117d83ef93.png)

... but I think "goodnight" is easier to understand than ":ablobgoodnightreverse:" and they could all have the same alt text.
- As for (iv), it is quite difficult to express this kind of strange emoji as text. I have never thought (iv) meant *sad*. They can be simply left as they are, without alt text.

Maybe some other communication apps (LINE?) had this kind of features. Alt text could be translated but that will be another issue.

**Comment by acid-chicken** [comment] 2023-02-03 09:14
Duplicate of #6457

**Closed as completed by acid-chicken** 2023-02-03 09:14 UTC
Labels: ✨Feature
