### ISSUE TITLE
Notification cannot be handled for deleted users

### ISSUE THREAD

**Issue by Astro-CQM** [syuilo/Misskey#13466] opened 2024-02-27 08:04 UTC
### 💡 Summary

request to `/api/i/notifications-grouped` is failed when there's notification from deleted user. (and also failed to show any notification while that noti is in first page)

### 🥰 Expected Behavior

return grouped notifications except from removed/muted/blocked users.

### 🤬 Actual Behavior

return 500 when there's notification from removed user (especially from remote)

### 📝 Steps to Reproduce

1. send any reaction/renote... etc to user
2. delete account
3. check user's notification

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): MacBook Air (M1, 2021), macOS Sonoma 14.4 (Beta 4)
* Browser: Chrome 122.0.6261.57 (ARM64)
* Server URL: psec.dev (but not limited to this instance)
* Misskey: 2024.2.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: systemd
* Misskey: 2024.2.0
* Node: 20.4.0
* PostgreSQL: 15.5
* Redis: 7.0.12
* OS and Architecture: Ubuntu 23.10 (AMD64)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1STEP621** [comment] 2024-02-27 10:56
Duplicate of #13369, #13430, #13454
WIP on #13284 (#13412)

**Closed as not planned** 2024-02-27 11:11 UTC
Labels: ⚠️bug?
