### ISSUE TITLE
Top menu layout doesn't work

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8354] opened 2022-02-25 08:14 UTC
## 💡 Summary

Selecting `Top` in the Menu portion of settings doesn't work

## 🥰 Expected Behavior

Buttons go to top of screen

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/155679329-c7e2728c-2d26-4679-8ed1-61b36dabdff9.png)

## 📝 Steps to Reproduce

1. Go to settings > menu
2. Select `Top`
3. Reload

> `Side (icons)` works fine

## 📌 Environment

Misskey version: 52ab5d8fef1adfa32a1c9ba1b67337a6889e3182
Your OS: Linux
Your browser: Librewolf

**Comment by Johann150** [comment] 2022-02-25 08:16
Duplicate of #8185

**Closed as completed by Johann150** 2022-02-25 08:16 UTC
