### ISSUE TITLE
Still able to see user after blocking, muting, AND suspending!

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8366] opened 2022-02-27 19:33 UTC
## 💡 Summary

I blocked, muted, and suspended the user in orange but I still see then on my timeline.

![Screenshot_20220227-112944__01__01__01.jpg](https://user-images.githubusercontent.com/44733677/155897414-c04fd7f4-fd57-4ccc-a136-751136e4c797.jpg)

## 📝 Steps to Reproduce

1. Block/mute/suspend user
2. Reload page
3. Go to local timeline, still see them

## 📌 Environment

Misskey version: 12.107.0
Your OS: Android
Your browser: Chromium

**Comment by ThatOneCalculator** [comment] 2022-02-27 19:38
I can even see them on 3rd party apps, this seems like a pretty big problem. 

![Screenshot_20220227-113747.jpg](https://user-images.githubusercontent.com/44733677/155897098-6f42927c-7add-4afb-be6e-60bcf4e125fd.jpg)

**Comment by Johann150** [comment] 2022-02-27 19:40
Duplicate of #6346

**Closed as completed by Johann150** 2022-02-27 19:40 UTC
Labels: ⚠️bug?

**Comment by ThatOneCalculator** [comment] 2022-02-27 19:45
I redacted the screenshot further, but I don't see anything derogatory :/

**Comment by ThatOneCalculator** [comment] 2022-02-27 19:47
Also @Johann150 I *did* actually search for my issue on the issues tab, but I didnt see the one you linked at all.
