### ISSUE TITLE
Chat/Direct Message panel pannel

### ISSUE THREAD

**Issue by parpok** [syuilo/Misskey#10446] opened 2023-03-31 19:36 UTC
## Feature Request Summary

Many social media platforms, such as Twitter, Mastodon, Instagram, and others, have a built-in direct message (DM) panel. However, many Fediverse apps treat DMs as an afterthought, treating them like a regular post, which can lead to a confusing user experience (UX). Wouldn't it be better if DMs had a separate page in the web UI menu, like everyone else does? This would definitely provide a cleaner experience, rather than mixing DMs with all other types of posts.

**Comment by futchitwo** [comment] 2023-04-03 11:03
FYI: You can list them in the direct post tab of the notification page.

**Comment by parpok** [comment] 2023-04-03 18:17
> FYI: You can list them in the direct post tab of the notification page.

Yes indeed that's a great point. However from UX standpoint it's hidden in notification panel so not many people will notice it's existence. Adding "Direct messages" element to add to sidebar would be a better idea.

**Comment by tamaina** [comment] 2023-11-26 14:31
Duplicate of  #12467

**Closed as not planned** 2023-11-26 14:32 UTC
Labels: ✨Feature
