### ISSUE TITLE
chat doesn't show newly typed messages unless you refresh

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#9013] opened 2022-07-17 10:29 UTC
## 💡 Summary

In Misskey 12.116.1 chat messages aren't updating without a refresh.
## 🥰 Expected Behavior

Type message into chat and send, and your message gets added to the chat at the bottom.
## 🤬 Actual Behavior

After sending a message, the chat sound plays but the message doesn't display until you reload the page.
## 📝 Steps to Reproduce

1. Type message into chat
2. Send it by pressing the button or hitting CTRL + Enter

## 📌 Environment

Misskey version: 12.116.1
Your OS: Windows 10
Your browser: Chrome, Firefox

**Comment by ThatOneCalculator** [comment] 2022-07-18 06:51
Duplicate of #8951, (will be) fixed by #8983

**Closed as not planned** 2022-07-18 18:49 UTC
Labels: ⚠️bug?
