### ISSUE TITLE
Images loaded from external site

### ISSUE THREAD

**Issue by medimikka** [syuilo/Misskey#8640] opened 2022-05-10 05:54 UTC
## 💡 Summary

In various locations around Misskey, images of Ai are loaded from a remote site. This is not immediately obvious to Admins and Users and results in the leaking of IP addresses to a third party. Within the European Union this is not within the confines of the law, unless clearly stated, elsewhere it's somewhat bad behavior since those requests can be used to track users.

## 🥰 Expected Behavior

Keep all assets locally and make telemetry optional in admin config.

## 🤬 Actual Behavior

Assets are loaded from remote, hard coded, hosts. There seems to be no real technical reason for this, meaning it is entirely used to track.

## 📝 Steps to Reproduce

1. Log into your instance
2. Open any page with a not found or info "_ghost" image
3. Observe where the assets are loaded from

**Comment by tamaina** [comment] 2022-05-10 05:57
Duplicate of  #7043

**Closed as completed by tamaina** 2022-05-10 05:57 UTC
