### ISSUE TITLE
Test Mail works, but registration + notification mails not

### ISSUE THREAD

**Issue by sevi-kun** [syuilo/Misskey#9743] opened 2023-01-28 13:43 UTC
## 💡 Summary

After enabeling the email server and populating it with smtp settings, the notification and registration feature doesn't work. Never worked for me. I'm using Misskey since v12 and I'm currently on 13.2.1.

## 🥰 Expected Behavior

Notification mails and registration mails sent to user.

## 🤬 Actual Behavior

No mail get's sent.

## 📝 Steps to Reproduce

1. Set up mail server
2. Try register a new user or activate notifiactions.
3. Wait for mail forever

## 📌 Environment

Docker compose.

Misskey version: 13.2.1
Your OS: Ubuntu 22.04

**Comment by zyoshoka** [comment] 2024-06-11 13:22
Duplicate of #9032.

**Closed as not planned by zyoshoka** 2024-06-11 13:22 UTC
Labels: ⚠️bug?
