### ISSUE TITLE
Hide or mark featured notes with "content warning"

### ISSUE THREAD

**Issue by yitsushi** [syuilo/Misskey#10415] opened 2023-03-26 05:19 UTC
## Summary

If a note has a content warning, most likely it is intentional and required or just simply inappropriate to show without consent. That's the essence of the content warning option. However on the front page posts with content warning are visible without any folding or marks.

I know - right now - the front page featured notes section is not interactive so folding is a no go short term, but adding an extra `andWhere` call to check if if has CW and exclude them from the front page would be good solution.

Semi-related to #6050

**Comment by zyoshoka** [comment] 2024-06-12 07:57
I'm closing this issue as a duplicate of #11221 since the discussion on the other issue is more active!

**Closed as not planned by zyoshoka** 2024-06-12 07:57 UTC
Labels: ✨Feature
