### ISSUE TITLE
Multi-line codeblocks don't appear in pages

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8938] opened 2022-07-05 07:22 UTC
## 💡 Summary

Multi-line code blocks

```
like
this
```

don't appear in pages.

## 🥰 Expected Behavior

They work like before

## 🤬 Actual Behavior

![image](https://user-images.githubusercontent.com/44733677/177272383-5eae9d6c-fccb-4c08-aeb1-b68ee384d597.png)
![image](https://user-images.githubusercontent.com/44733677/177272406-282da208-2131-452e-b315-b14850f13aee.png)

https://stop.voring.me/@thatonecalculator/pages/1657005575665/view-source

## 📌 Environment

Misskey version: 12.112.0-beta.16
Your OS: Linux
Your browser: Firefox

**Comment by Johann150** [comment] 2022-07-05 22:32
Duplicate of #8944

**Closed as not planned by Johann150** 2022-07-05 22:32 UTC
Labels: packages/frontend, ⚠️bug?
