### ISSUE TITLE
Twitter crossposting

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8171] opened 2022-01-21 23:47 UTC
## Summary

Since there is already Twitter integration, Twitter crossposting would help a lot of people new to Misskey coming from Twitter to still connect with their friends on Twitter without having to go to Twitter ***and*** Misskey to post to everyone.

**Comment by Johann150** [comment] 2022-01-29 23:35
First of all I dislike this idea of trying to be in both spheres at once. Also I think it is too complex for Misskey to implement a complete Twitter client by itself and you should use a separate software.

**Comment by ThatOneCalculator** [comment] 2022-01-30 04:31
The problem is, unlike Mastodon (and moa.party), there are no Misskey <-> Twitter crossposters (at least that I'm aware of). Plus, you can already sign into your Twitter account thru Misskey.

**Comment by 4ioskd** [comment] 2022-02-19 14:39
Related to #6132 ?
twitter crossposting isn't needed. Misskey is Misskey. Twitter is Twitter.
if you want to crosspost for Misskey and Twitter, you should separetely use each clients.

**Comment by tamaina** [comment] 2022-02-19 14:40
Duplicate of #6132

**Closed as completed by tamaina** 2022-02-19 14:40 UTC
Labels: ✨Feature

**Comment by ThatOneCalculator** [comment] 2022-02-19 20:07
> Related to #6132 ?
> twitter crossposting isn't needed. Misskey is Misskey. Twitter is Twitter.
> if you want to crosspost for Misskey and Twitter, you should separetely use each clients.

The thing is, I'd rather have one place to share my thoughts. I've left Twitter, but still have ~1500 followers who still might want to hear what I have to say. Just because they're seperate doesn't mean they shouldn't be interoperable.
