### ISSUE TITLE
Server Metrics Widget Disk tab on ARM Server displays efivars device stats

### ISSUE THREAD

**Issue by aliceif** [syuilo/Misskey#14525] opened 2024-09-08 20:05 UTC
### Summary

The Server Metric Widget on my CAX21 VPS from Hetzner shows the statistics for the efivars file system in the Disk statistics. This is not very useful, it would probably be more useful to use the biggest drive or an average over all disks instead of the first disk that the systeminformation package finds (I think this is what misskey currently does in the code).

Example:
![image](https://github.com/user-attachments/assets/6a10876c-63b2-4741-b79f-e1babab9a66b)

```sh
$  df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           773M  2.4M  771M   1% /run
efivarfs        256K   18K  239K   7% /sys/firmware/efi/efivars
/dev/sda1        75G   26G   47G  36% /
tmpfs           3.8G  2.1M  3.8G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      253M  6.4M  246M   3% /boot/efi
tmpfs           773M   12K  773M   1% /run/user/1000
$
```

### Purpose

It will help administrators keep an eye on their server's storage usage.

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by KisaragiEffective** [comment] 2024-09-08 20:09
Duplicate of #13573

**Closed as not planned by KisaragiEffective** 2024-09-08 20:09 UTC
Labels: 🐛Bug, packages/backend
