### ISSUE TITLE
Page administration feature request

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#10355] opened 2023-03-18 12:48 UTC
## Summary

**As administrator I want to edit and delete other's local pages instead of deleting the whole other local account**

Actually, viewing as administrator, any local page made by any local account, gives you only ability for duplication activity.
Administrators can see editing page but they have no button for edit / delete / unpublish

This feature request asks for introduction of button "delete" and "edit" for administrators, or role capability who can be assigned to custom roles.

Misskey version 13.9.2

**Comment by futchitwo** [comment] 2023-03-19 09:59
duplicate of #10280 ?

**Comment by tassoman** [comment] 2023-03-19 10:47
はい、そうですね、英語も　 🙄 😆

**Closed as not planned** 2024-01-16 13:15 UTC
Labels: ✨Feature
