### ISSUE TITLE
エラーが発生しました for older browsers

### ISSUE THREAD

**Issue by misskey-bugreporter** [syuilo/Misskey#8939] opened 2022-07-05 15:02 UTC
## 💡 Summary

Misskey web-client fails to load for older browsers.

## 🥰 Expected Behavior

Misskey is loaded.

## 🤬 Actual Behavior

An error is shown:

```
⚠エラーが発生しました

問題が解決しない場合は管理者までお問い合わせください。以下のオプションを試すこともできます:

    [簡易クライアント](https://misskey.weebcouncil.online/cli)を起動
    [BIOS](https://misskey.weebcouncil.online/bios)で修復を試みる
    [キャッシュをクリア](https://misskey.weebcouncil.online/flush)する

ERROR CODE: APP_FETCH_FAILED
Details:
{}
```

## 📝 Steps to Reproduce

1. Initialize a new profile in an older browser.
2. Visit any recently updated Misskey instance (e.g. https://misskey.ranranhome.info/).

## 📌 Environment

Misskey version: 12.111.1
Your OS: GNU/Linux
Your browser: Mozilla Firefox 78.0

**Comment by rinsuki** [comment] 2022-07-05 15:03
duplicate of #8603

**Closed as not planned by rinsuki** 2022-07-05 15:03 UTC
Labels: ⚠️bug?

**Comment by misskey-bugreporter** [comment] 2022-07-05 15:12
Some investigation show that the error is:

```
...
t: SyntaxError
​​   columnNumber: 2493
​​   fileName: "https://misskey.ranranhome.info/assets/app.aadfcf61.js"
​​   lineNumber: 1
​​   message: "await is a reserved identifier"
​​   stack: ""
...
```
