### ISSUE TITLE
changing CSS for the whole site

### ISSUE THREAD

**Issue by ooozerooo** [syuilo/Misskey#8728] opened 2022-05-24 03:53 UTC
I want to change the emoji scaling for my site (want custom emojis to be smaller) but found that you could only change it for yourself on the frontend  in `settings>general>custom css`. I tried to change the code in `packages/client/src/components/global/emoji.vue` as well
```
<style lang="scss" scoped>
.mk-emoji {
        height: 1.5em;
        vertical-align: -0.25em;

        &.custom {
                height: 1.5em;
                vertical-align: middle;
                transition: transform 0.2s ease;

                &:hover {
                        transform: scale(2.2);
                }

                &.normal {
                        height: 1.5em;
                        vertical-align: -0.25em;

                        &:hover {
                                transform: none;
                        }
                }
        }

        &.noStyle {
                height: auto !important;
        }
}
</style>
```
However, it doesn't appear to have any effect on the website (I have restarted misskey). Did I look at the wrong file or is there something else to change? Also I wish there is a custom css feature in the control panel too, it would be nice if admins can change it more easily for the whole site.

Thank you.

**Comment by ThatOneCalculator** [comment] 2022-05-24 04:21
If you're rebuilding the client, you need to increase the version number in `package.json` (i.e. changing it from `12.110.1` to `12.110.1-1`.)

**Comment by Johann150** [comment] 2022-05-24 06:07
When you rebuild Misskey without changing the version number you may have to clear your browser's cache and/or web server cache (if enabled) for the results to become visible.

In regards to allowing Admin to change CSS, this is a duplicate of #7143.

**Closed as completed by Johann150** 2022-05-24 06:07 UTC
