### ISSUE TITLE
Following/Followers count not computed properly

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8544] opened 2022-04-25 04:43 UTC
## 💡 Summary

There are some local users that show 0 followers/0 following, where that information is wrong.

## 🥰 Expected Behavior

Correct numbers

## 🤬 Actual Behavior

Notice how both are local users (@stop.voring.me)

![image](https://user-images.githubusercontent.com/44733677/165022133-866c94b2-39eb-4770-96f5-146bcf47de33.png)

![image](https://user-images.githubusercontent.com/44733677/165022157-c0745dd8-fcb7-49b7-a225-f6af23a0286c.png)

## 📌 Environment

Misskey version: 12.110.1
Your OS: Linux
Your browser: Firefox, happens on all browsers

**Comment by ThatOneCalculator** [comment] 2022-04-25 04:44
Most likely related to #8543. There should be a way to have the server recalculate the counts.

**Comment by Johann150** [comment] 2022-04-25 05:34
Duplicate of #8516

**Closed as completed by Johann150** 2022-04-25 05:34 UTC

**Comment by ThatOneCalculator** [comment] 2022-04-25 05:50
> Duplicate of #8516

Ah. At first, I thought it was unrelated (given 8516 is about remote users and this is about local when followers wasn't processed correctly).

**Comment by ThatOneCalculator** [comment] 2022-04-25 05:51
Actually @Johann150 , I feel there still *should* be a way for admins to manually refresh the following/follower count of a user.
