### ISSUE TITLE
missplaced emoji button on reply modal window

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#10433] opened 2023-03-28 21:41 UTC
## 💡 Summary

emoji button jumped off actions buttons to go nowhere inside the message textarea

## 🥰 Expected Behavior

I expected to find the emoji button where it was previously

## 🤬 Actual Behavior

![immagine](https://user-images.githubusercontent.com/92727/228372829-80bccbf2-2104-4a8d-90e4-b9ed460a3706.png)

## 📝 Steps to Reproduce

1. click reply button on a note  ↩️
2. see: missplaced emoji button overlapping post visibility icon

## 📌 Environment

Misskey version: 13.10.3
Your OS: docker
Your browser: any

**Comment by acid-chicken** [comment] 2023-03-29 01:13
Duplicate of #10390

**Closed as not planned by acid-chicken** 2023-03-29 01:13 UTC
