### ISSUE TITLE
Scheduled automatic deletion of notes / posts

### ISSUE THREAD

**Issue by robflop** [syuilo/Misskey#9297] opened 2022-12-08 06:16 UTC
## Summary

I'd like for there to be an option to have your notes be automatically deleted after a set period of time (with some customization options like a week, a month, 6 months, a year and such as well as a feature to exclude specified posts from deletion, for example via reacting to a post of yours you want te exclude with a set reaction). As time passes and we use our accounts on Misskey (and the Fediverse at large), we amass quite an amount of notes created, not all of which we may want to remain on the internet for all eternity (or not all of which even have value to remain). That's why having a scheduled deletion of posts would be good to have, so that you can avoid building up a backlog of years' worth of notes that you may have written at some point in time but totally forgotten about.

This feature is largely inspired by codl's forget website which previously fulfilled this job for a range of Fediverse platforms including Misskey: https://forget.codl.fr/notice.html

Mastodon already implements a feature like this (also based on codl's forget): https://github.com/mastodon/mastodon/pull/16529

The "post deletion policy" explained in the above PR looks like a good place to look at for inspiration on the configurability of this feature besides a binary "on/off" too.

**Comment by acid-chicken** [comment] 2022-12-08 14:32
Duplicate of #5229

**Closed as not planned** 2022-12-08 14:33 UTC
Labels: ✨Feature
