### ISSUE TITLE
The ability to change username / Use username from previously deleted account

### ISSUE THREAD

**Issue by Ekanyani** [syuilo/Misskey#13103] opened 2024-01-28 11:40 UTC
### Summary

As the title suggest

### Purpose

Its for those that got bored with their current username / have deleted their account and now wanting to use that username back.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by kakkokari-gtyih** [comment] 2024-01-28 16:19
I think it's virtually impossible because of the spec of federation

**Comment by Mar0xy** [comment] 2024-01-28 20:04
Exactly as Kakkokari said changing username is not a supported feature of ActivityPub

**Comment by acid-chicken** [comment] 2024-01-28 20:11
Duplicate of #11372

**Closed as not planned** 2024-01-28 20:12 UTC

**Comment by Ekanyani** [comment] 2024-01-29 10:24
> I think it's virtually impossible because of the spec of federation (changing username can result in confusion on remote servers)

What about a feature to regain username from previously deleted user?
