### ISSUE TITLE
ユーザー検索の時に入力欄に記入し直すと結果に反映されない場合がある

### ISSUE THREAD

**Issue by At-sushi** [syuilo/Misskey#8864] opened 2022-06-22 10:42 UTC
## 💡 Summary

"Search Users" tab may doesn't work when the input box has been refilled.

## 🥰 Expected Behavior

It is expected to rerun search system and show the new results.

## 🤬 Actual Behavior

The page doesn't show the new results, instead the page doesn't update at all.

## 📝 Steps to Reproduce

1. Open Discover page, then open "Search Users" tab.
2. fill the input box something.
3. when the page should the results, retype some texts into the input box.

## 📌 Environment

Misskey version: 12.110.1
Your OS: Mac OS X Catalina 10.15.7
Your browser: Safari 15.5 (15613.2.7.1.9, 15613)

This might be browser specific issue. May fix if I can.

**Comment by Johann150** [comment] 2022-06-23 07:21
Duplicate of #8711

**Closed as not planned by Johann150** 2022-06-23 07:21 UTC
Labels: ⚠️bug?
