### ISSUE TITLE
Follow request notifications may get lost

### ISSUE THREAD

**Issue by cromachina** [syuilo/Misskey#14791] opened 2024-10-19 17:11 UTC
### 💡 Summary

I tried reporting this on misskey.io zendesk, however they suggested reporting here instead. Follow requests do not all appear when filtering notifications, and follow requests may get lost when older notifications are purged.

### 🥰 Expected Behavior

Follow requests should probably be retained forever until accepted or rejected, or maybe have a different UI component to allow users to service their follow requests. Filtered notifications should at least show all follow requests that have not yet been purged from your notifications (or perhaps show all retained requests that have not been accepted or rejected).

### 🤬 Actual Behavior

If you have a lot of notifications, follow requests (which seem to be generated from other servers) can get buried in the notifications, and may even be lost when older notifications are purged. If you select a filter for notifications to only show follow requests, many of the requests that were in the full notification list do not appear for an unknown reason.

### 📝 Steps to Reproduce

1. Have a LOT of notifications (probably the maximum possible?)
2. Scroll through notifications and observe any follow requests
3. Select filter for notifications and filter by follow requests
4. Observe that only a few of the last follow requests may even appear, instead of all of them.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Linux PC
* Browser: Firefox 130
* Server URL: https://misskey.io/
* Misskey: 2024.5.0-io.3a
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by Sayamame-beans** [comment] 2024-10-20 01:42
If you are using "Follow requests require approval" option, you should see "Follow requests" menu on the left menu bar,
Is it not displayed?

**Comment by cromachina** [comment] 2024-10-20 01:47
I'm not using that feature, however the server misskey.io, has set it so that useds from specific remote instances always generate follow requests, of which there is no way to override or supersede that behavior as a user. It would be nice if I could just say "I don't care, just approve follow requests automatically anyway" if the server was configured to do that for specific remote instances.

**Comment by Sayamame-beans** [comment] 2024-10-20 01:51
OK, so it is caused with server silence, etc...
This is duplicate of #12268, I think.
Thank you for reporting!

**Closed as not planned by Sayamame-beans** 2024-10-20 01:51 UTC
Labels: ⚠️bug?
