### ISSUE TITLE
Draft feature

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8881] opened 2022-06-23 18:32 UTC
## Summary

The ability to save a post as a draft and post it later would be very helpful

**Comment by tamaina** [comment] 2022-06-23 18:34
Duplicate of #7098

**Closed as not planned by tamaina** 2022-06-23 18:34 UTC
Labels: ✨Feature

**Comment by ThatOneCalculator** [comment] 2022-06-23 18:38
Huh, I searched "Draft" in issues but that didn't pop up... thanks GitHub :facepalm:
