### ISSUE TITLE
this.renderChart is not a function

### ISSUE THREAD

**Issue by cliqsocial** [syuilo/Misskey#8083] opened 2021-12-22 21:35 UTC
## 💡 Summary

this.renderChart is not a function

## 🙂 Expected Behavior

no errors

## ☹️ Actual Behavior

<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: this.renderChart is not a function
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Proxy.&lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" title="https://cliq.social/assets/8173.12.100.2.js:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">8173.12.100.2.js:1</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono, monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonymous) | @ | 8173.12.100.2.js:1
-- | -- | -- | --
  | Promise.then (async) |   |  
  | $n | @ | app.12.100.2.js:2
  | (anonymous) | @ | 8173.12.100.2.js:1
  | Promise.then (async) |   |  
  | created | @ | 8173.12.100.2.js:1
  | wn | @ | app.12.100.2.js:2
  | _n | @ | app.12.100.2.js:2
  | he | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | dn | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | sn | @ | app.12.100.2.js:2
  | z | @ | app.12.100.2.js:2
  | D | @ | app.12.100.2.js:2
  | y | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | run | @ | app.12.100.2.js:2
  | wn | @ | app.12.100.2.js:2
  | Hn | @ | app.12.100.2.js:2
  | Promise.then (async) |   |  
  | Ln | @ | app.12.100.2.js:2
  | Nn | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | D | @ | app.12.100.2.js:2
  | je | @ | app.12.100.2.js:2
  | set value | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | Promise.then (async) |   |  
  | setup | @ | app.12.100.2.js:2
  | wn | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | sn | @ | app.12.100.2.js:2
  | z | @ | app.12.100.2.js:2
  | D | @ | app.12.100.2.js:2
  | y | @ | app.12.100.2.js:2
  | A | @ | app.12.100.2.js:2
  | I | @ | app.12.100.2.js:2
  | y | @ | app.12.100.2.js:2
  | A | @ | app.12.100.2.js:2
  | O | @ | app.12.100.2.js:2
  | C | @ | app.12.100.2.js:2
  | y | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | run | @ | app.12.100.2.js:2
  | wn | @ | app.12.100.2.js:2
  | Hn | @ | app.12.100.2.js:2
  | Promise.then (async) |   |  
  | Ln | @ | app.12.100.2.js:2
  | Nn | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | D | @ | app.12.100.2.js:2
  | I | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | e.<computed> | @ | app.12.100.2.js:2
  | navigate | @ | 5877.12.100.2.js:1
  | navHook | @ | 5877.12.100.2.js:1
  | nav | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | (anonymous) | @ | app.12.100.2.js:2
  | wn | @ | app.12.100.2.js:2
  | _n | @ | app.12.100.2.js:2
  | n | @ | app.12.100.2.js:2

</span></div>

## 📝 Steps to Reproduce

1. Sign in
2. Click on Settings
3. Click on Drive

## 📌 Environment

12.100.2 / PostgreSQL 13.4 / nginx

**Comment by tamaina** [comment] 2021-12-23 15:23
再現した

**Comment by zyoshoka** [comment] 2024-07-09 14:57
Caused by https://github.com/misskey-dev/misskey/commit/26928ab407902a52ddd3e801708007683b41a648

Fixed by https://github.com/misskey-dev/misskey/commit/fc02f8fc93635e83273e8687c03356c185c20348

**Closed as completed by zyoshoka** 2024-07-09 14:57 UTC
Labels: 🐛Bug, packages/frontend
