### ISSUE TITLE
Notes sent with Fan-out Timeline Technology (FTT) disabled not showing in user profile.

### ISSUE THREAD

**Issue by rakino** [syuilo/Misskey#12271] opened 2023-11-06 11:51 UTC
### 💡 Summary

Two test notes:
![image](https://github.com/misskey-dev/misskey/assets/26847027/85cf3b7b-2d3d-4a28-ad17-04c6da2c47d7)

In user profile, only the one sent with FTT enabled is shown, even when FTT is disabled.
![image](https://github.com/misskey-dev/misskey/assets/26847027/05937fd0-378a-4810-923e-2f4b49bb34e9)

### 🥰 Expected Behavior

All new notes should be shown in user profile.

### 🤬 Actual Behavior

Only the ones sent with FTT enabled are shown.

### 📝 Steps to Reproduce

1. Disable FTT in admin/settings.
2. Send a note.
3. Check your profile.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL: social.boiledscript.com
* Misskey: 2023.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey: (docker) 2023.11.0
* Node:
* PostgreSQL: (docker) postgres:15-alpine
* Redis: (docker) redis:alpine
* OS and Architecture: Debian GNU/Linux 12 (bookworm) aarch64
```

**Comment by zyoshoka** [comment] 2024-06-18 08:29
Seems to be duplicate of #12126.

**Closed as not planned by zyoshoka** 2024-06-18 08:29 UTC
Labels: ⚠️bug?
