### ISSUE TITLE
Sidebar can't be opened properly

### ISSUE THREAD

**Issue by ShadowRZ** [syuilo/Misskey#9487] opened 2023-01-07 13:05 UTC
## 💡 Summary

The sidebar can't be opened properly and only shows a black background: https://img.yoitsu.moe/f6/34f895e0bfbb07af5177e57ec1091c4b3e31a4.png

## 🥰 Expected Behavior

The sidebar can open properly and show something.

## 🤬 Actual Behavior

Only a black background occurs: https://img.yoitsu.moe/f6/34f895e0bfbb07af5177e57ec1091c4b3e31a4.png

## 📝 Steps to Reproduce

1. Resize the browser window so the sidebar button can be seen.
2. Click on the sidebar button.

## 📌 Environment

Misskey version: v13.0.0-beta.27
Your OS: Microsoft Windows
Your browser: Chromium 107.0.5304.107 (Official Build, ungoogled-chromium)

**Comment by caipira113** [comment] 2023-01-07 13:10
Updating the browser to version 108 may solve the problem, which is identified as #9187 in Chrome.

**Comment by tamaina** [comment] 2023-01-07 13:12
Duplicate of #9187

**Closed as not planned** 2023-01-07 13:12 UTC
Labels: ⚠️bug?
